### ISSUE TITLE
CRA LRA for prokaryotic genomes?

### ISSUE THREAD

**Issue by jianshu93** [Jingwen7/CRA#1]
Hello Jingwen,

This is Jianshu a Bioinformatics phd student at Georgia Tech, studying long reads for bacterial and arcahea genomes from environment. I am comparing LRA to both improved minimap2: New strategies to improve minimap2 alignment accuracy and winnowmap for prokaryotes (no genomic repeats). Is this CRA an improved version. I do not see readme file and failed compiling it. All the testing are based on human genomes/eukaryotic genomes right, including SV?  Please let me know whether you want to discuss more (my WeChat is JansueChao ). 

Thanks,

Jianshu

**Comment by Jingwen7** [comment]
Hi Jianshu, 

The LRA repository is located here: https://github.com/ChaissonLab/LRA. This CRA repository is my new project which is not long read aligner. I haven't add readme yet. Sorry for the confusion.
For you question "All the testing are based on human genomes/eukaryotic genomes right, including SV?". Yes, the LRA paper measured the accuracy of detecting SV only on human genomes. 
 I'm glad to see you are applying LRA to bacterial and arcahea genomes. Please reach out if you have question about LRA. :)

**Comment by jianshu93** [comment]
I will close this issue then. And I will let you know how it looks like for bacterial and archaea genome. Do you have the access to material in information retrieving and search engine website class？ I did not found very good online material on nearest neighbour search but this class syllabus (https://csci572.com) mentioned it and I see you took it. I am doing nearest genome search in database based on hierarchical navigable small world graph. Not quite sure whether it is appropriate to ask but anyway thanks for your help.
